version: 2

sources:
  - name: dw_northwind
    tables:
      - name: public_orders
      - name: public_products
      - name: public_shippers
      - name: public_suppliers
      - name: public_customers
      - name: public_employees
      - name: public_order_details
      - name: public_categories